-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vid_oe4_v_tpg_0_0_tpgForeground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    bckgndYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_empty_n : IN STD_LOGIC;
    bckgndYUV_read : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    ovrlayId : IN STD_LOGIC_VECTOR (7 downto 0);
    maskId : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat : IN STD_LOGIC_VECTOR (7 downto 0);
    crossHairX : IN STD_LOGIC_VECTOR (15 downto 0);
    crossHairY : IN STD_LOGIC_VECTOR (15 downto 0);
    boxSize : IN STD_LOGIC_VECTOR (15 downto 0);
    boxColorR : IN STD_LOGIC_VECTOR (15 downto 0);
    boxColorG : IN STD_LOGIC_VECTOR (15 downto 0);
    boxColorB : IN STD_LOGIC_VECTOR (15 downto 0);
    motionSpeed : IN STD_LOGIC_VECTOR (7 downto 0);
    ovrlayYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_full_n : IN STD_LOGIC;
    ovrlayYUV_write : OUT STD_LOGIC );
end;


architecture behav of vid_oe4_v_tpg_0_0_tpgForeground is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_F0 : STD_LOGIC_VECTOR (7 downto 0) := "11110000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal boxHCoord : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal boxVCoord : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tobool_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool_reg_411 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_222_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_reg_421 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_fu_232_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_reg_446 : STD_LOGIC_VECTOR (7 downto 0);
    signal hMax_fu_240_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal hMax_reg_451 : STD_LOGIC_VECTOR (15 downto 0);
    signal vMax_fu_246_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal vMax_reg_456 : STD_LOGIC_VECTOR (15 downto 0);
    signal and4_i_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and4_i_reg_461 : STD_LOGIC_VECTOR (0 downto 0);
    signal and10_i_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and10_i_reg_466 : STD_LOGIC_VECTOR (0 downto 0);
    signal and26_i_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and26_i_reg_471 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_67_fu_290_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_67_reg_476 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_481 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_68_fu_310_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_68_reg_486 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_i_fu_314_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_i_reg_491 : STD_LOGIC_VECTOR (8 downto 0);
    signal y_1_reg_496 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal boxVCoord_loc_0_load_reg_504 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln727_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxHCoord_loc_0_load_reg_509 : STD_LOGIC_VECTOR (15 downto 0);
    signal cmp2_i_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp2_i_reg_514 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_start : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_done : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_idle : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_ready : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_bckgndYUV_read : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ovrlayYUV_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ovrlayYUV_write : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord_loc_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord_loc_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord_loc_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord_loc_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord_ap_vld : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord_ap_vld : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm_state3 : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal boxHCoord_loc_0_fu_98 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxVCoord_loc_0_fu_94 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_fu_90 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_2_fu_353_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal cmp31_i_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_66_fu_252_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_262_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_276_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_294_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vid_oe4_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bckgndYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_empty_n : IN STD_LOGIC;
        bckgndYUV_read : OUT STD_LOGIC;
        ovrlayYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_full_n : IN STD_LOGIC;
        ovrlayYUV_write : OUT STD_LOGIC;
        boxHCoord_loc_0 : IN STD_LOGIC_VECTOR (15 downto 0);
        boxVCoord_loc_0 : IN STD_LOGIC_VECTOR (15 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
        pixOut_val_V_9 : IN STD_LOGIC_VECTOR (7 downto 0);
        pixOut_val_V : IN STD_LOGIC_VECTOR (7 downto 0);
        pixOut_val_V_7 : IN STD_LOGIC_VECTOR (7 downto 0);
        and4_i : IN STD_LOGIC_VECTOR (0 downto 0);
        and26_i : IN STD_LOGIC_VECTOR (0 downto 0);
        tobool : IN STD_LOGIC_VECTOR (0 downto 0);
        and10_i : IN STD_LOGIC_VECTOR (0 downto 0);
        ovrlayId_load : IN STD_LOGIC_VECTOR (7 downto 0);
        boxSize_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        zext_ln1869 : IN STD_LOGIC_VECTOR (7 downto 0);
        vMax : IN STD_LOGIC_VECTOR (15 downto 0);
        hMax : IN STD_LOGIC_VECTOR (15 downto 0);
        zext_ln1869_1 : IN STD_LOGIC_VECTOR (8 downto 0);
        cmp101_i : IN STD_LOGIC_VECTOR (0 downto 0);
        boxColorG_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        crossHairX_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp2_i : IN STD_LOGIC_VECTOR (0 downto 0);
        color : IN STD_LOGIC_VECTOR (7 downto 0);
        boxHCoord_loc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxHCoord_loc_1_out_ap_vld : OUT STD_LOGIC;
        boxVCoord_loc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxVCoord_loc_1_out_ap_vld : OUT STD_LOGIC;
        boxHCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxHCoord_ap_vld : OUT STD_LOGIC;
        boxVCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxVCoord_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174 : component vid_oe4_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_start,
        ap_done => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_done,
        ap_idle => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_idle,
        ap_ready => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_ready,
        bckgndYUV_dout => bckgndYUV_dout,
        bckgndYUV_num_data_valid => ap_const_lv5_0,
        bckgndYUV_fifo_cap => ap_const_lv5_0,
        bckgndYUV_empty_n => bckgndYUV_empty_n,
        bckgndYUV_read => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_bckgndYUV_read,
        ovrlayYUV_din => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ovrlayYUV_din,
        ovrlayYUV_num_data_valid => ap_const_lv5_0,
        ovrlayYUV_fifo_cap => ap_const_lv5_0,
        ovrlayYUV_full_n => ovrlayYUV_full_n,
        ovrlayYUV_write => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ovrlayYUV_write,
        boxHCoord_loc_0 => boxHCoord_loc_0_load_reg_509,
        boxVCoord_loc_0 => boxVCoord_loc_0_load_reg_504,
        loopWidth => width,
        pixOut_val_V_9 => empty_68_reg_486,
        pixOut_val_V => pixOut_val_V_reg_446,
        pixOut_val_V_7 => empty_67_reg_476,
        and4_i => and4_i_reg_461,
        and26_i => and26_i_reg_471,
        tobool => tobool_reg_411,
        and10_i => and10_i_reg_466,
        ovrlayId_load => ovrlayId,
        boxSize_1 => boxSize,
        y => y_1_reg_496,
        zext_ln1869 => motionSpeed,
        vMax => vMax_reg_456,
        hMax => hMax_reg_451,
        zext_ln1869_1 => shl_i_reg_491,
        cmp101_i => icmp_reg_481,
        boxColorG_1 => empty_reg_421,
        crossHairX_1 => crossHairX,
        cmp2_i => cmp2_i_reg_514,
        color => colorFormat,
        boxHCoord_loc_1_out => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord_loc_1_out,
        boxHCoord_loc_1_out_ap_vld => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord_loc_1_out_ap_vld,
        boxVCoord_loc_1_out => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord_loc_1_out,
        boxVCoord_loc_1_out_ap_vld => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord_loc_1_out_ap_vld,
        boxHCoord => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord,
        boxHCoord_ap_vld => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord_ap_vld,
        boxVCoord => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord,
        boxVCoord_ap_vld => grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln727_fu_348_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state3) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_ready = ap_const_logic_1)) then 
                    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    boxHCoord_loc_0_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                boxHCoord_loc_0_fu_98 <= boxHCoord;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord_loc_1_out_ap_vld = ap_const_logic_1))) then 
                boxHCoord_loc_0_fu_98 <= grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord_loc_1_out;
            end if; 
        end if;
    end process;

    boxVCoord_loc_0_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                boxVCoord_loc_0_fu_94 <= boxVCoord;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord_loc_1_out_ap_vld = ap_const_logic_1))) then 
                boxVCoord_loc_0_fu_94 <= grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord_loc_1_out;
            end if; 
        end if;
    end process;

    y_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_90 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln727_fu_348_p2 = ap_const_lv1_0))) then 
                y_fu_90 <= y_2_fu_353_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                and10_i_reg_466 <= and10_i_fu_270_p2;
                and26_i_reg_471 <= and26_i_fu_284_p2;
                and4_i_reg_461 <= and4_i_fu_256_p2;
                empty_67_reg_476 <= empty_67_fu_290_p1;
                empty_68_reg_486 <= empty_68_fu_310_p1;
                empty_reg_421 <= empty_fu_222_p1;
                hMax_reg_451 <= hMax_fu_240_p2;
                icmp_reg_481 <= icmp_fu_304_p2;
                    pixOut_val_V_reg_446(6 downto 4) <= pixOut_val_V_fu_232_p3(6 downto 4);
                    shl_i_reg_491(8 downto 1) <= shl_i_fu_314_p3(8 downto 1);
                tobool_reg_411 <= tobool_fu_216_p2;
                vMax_reg_456 <= vMax_fu_246_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord_ap_vld = ap_const_logic_1))) then
                boxHCoord <= grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxHCoord;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln727_fu_348_p2 = ap_const_lv1_0))) then
                boxHCoord_loc_0_load_reg_509 <= boxHCoord_loc_0_fu_98;
                boxVCoord_loc_0_load_reg_504 <= boxVCoord_loc_0_fu_94;
                cmp2_i_reg_514 <= cmp2_i_fu_365_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord_ap_vld = ap_const_logic_1))) then
                boxVCoord <= grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_boxVCoord;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                y_1_reg_496 <= y_fu_90;
            end if;
        end if;
    end process;
    pixOut_val_V_reg_446(3 downto 0) <= "0000";
    pixOut_val_V_reg_446(7) <= '1';
    shl_i_reg_491(0) <= '0';

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln727_fu_348_p2, grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln727_fu_348_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    and10_i_fu_270_p2 <= (tmp_fu_262_p3 and cmp31_i_fu_226_p2);
    and26_i_fu_284_p2 <= (tmp_2_fu_276_p3 and cmp31_i_fu_226_p2);
    and4_i_fu_256_p2 <= (empty_66_fu_252_p1 and cmp31_i_fu_226_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_NS_fsm_state3 <= ap_NS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_done)
    begin
        if ((grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln727_fu_348_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln727_fu_348_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    bckgndYUV_read_assign_proc : process(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_bckgndYUV_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bckgndYUV_read <= grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_bckgndYUV_read;
        else 
            bckgndYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    cmp2_i_fu_365_p2 <= "1" when (y_fu_90 = crossHairY) else "0";
    cmp31_i_fu_226_p2 <= "1" when (colorFormat = ap_const_lv8_0) else "0";
    empty_66_fu_252_p1 <= maskId(1 - 1 downto 0);
    empty_67_fu_290_p1 <= boxColorR(8 - 1 downto 0);
    empty_68_fu_310_p1 <= boxColorB(8 - 1 downto 0);
    empty_fu_222_p1 <= boxColorG(8 - 1 downto 0);
    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_start <= grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ap_start_reg;
    hMax_fu_240_p2 <= std_logic_vector(unsigned(width) - unsigned(boxSize));
    icmp_fu_304_p2 <= "0" when (tmp_3_fu_294_p4 = ap_const_lv7_0) else "1";
    icmp_ln727_fu_348_p2 <= "1" when (y_fu_90 = height) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln727_fu_348_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln727_fu_348_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ovrlayYUV_din <= grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ovrlayYUV_din;

    ovrlayYUV_write_assign_proc : process(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ovrlayYUV_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ovrlayYUV_write <= grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_174_ovrlayYUV_write;
        else 
            ovrlayYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    pixOut_val_V_fu_232_p3 <= 
        ap_const_lv8_F0 when (cmp31_i_fu_226_p2(0) = '1') else 
        ap_const_lv8_80;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    shl_i_fu_314_p3 <= (motionSpeed & ap_const_lv1_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_2_fu_276_p3 <= maskId(2 downto 2);
    tmp_3_fu_294_p4 <= colorFormat(7 downto 1);
    tmp_fu_262_p3 <= maskId(1 downto 1);
    tobool_fu_216_p2 <= "1" when (maskId = ap_const_lv8_0) else "0";
    vMax_fu_246_p2 <= std_logic_vector(unsigned(height) - unsigned(boxSize));
    y_2_fu_353_p2 <= std_logic_vector(unsigned(y_fu_90) + unsigned(ap_const_lv16_1));
end behav;
