# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/DDR3_provided_files/urbana_ddr3.xdc

# Block Designs: bd/vid_oe1/vid_oe1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1 || ORIG_REF_NAME==vid_oe1} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_mig_7series_0_0/vid_oe1_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_mig_7series_0_0 || ORIG_REF_NAME==vid_oe1_mig_7series_0_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_axi_vdma_0_0/vid_oe1_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_axi_vdma_0_0 || ORIG_REF_NAME==vid_oe1_axi_vdma_0_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_axi_smc_0/vid_oe1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_axi_smc_0 || ORIG_REF_NAME==vid_oe1_axi_smc_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_rst_mig_7series_0_83M_0/vid_oe1_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==vid_oe1_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_v_axi4s_vid_out_0_0/vid_oe1_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==vid_oe1_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_hdmi_tx_0_0/vid_oe1_hdmi_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_hdmi_tx_0_0 || ORIG_REF_NAME==vid_oe1_hdmi_tx_0_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_clk_wiz_0_0/vid_oe1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_clk_wiz_0_0 || ORIG_REF_NAME==vid_oe1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_v_tpg_0_0/vid_oe1_v_tpg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_v_tpg_0_0 || ORIG_REF_NAME==vid_oe1_v_tpg_0_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_microblaze_0_1/vid_oe1_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_microblaze_0_1 || ORIG_REF_NAME==vid_oe1_microblaze_0_1} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_dlmb_v10_0/vid_oe1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_dlmb_v10_0 || ORIG_REF_NAME==vid_oe1_dlmb_v10_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_ilmb_v10_0/vid_oe1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_ilmb_v10_0 || ORIG_REF_NAME==vid_oe1_ilmb_v10_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_dlmb_bram_if_cntlr_0/vid_oe1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==vid_oe1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_ilmb_bram_if_cntlr_0/vid_oe1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==vid_oe1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_lmb_bram_0/vid_oe1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_lmb_bram_0 || ORIG_REF_NAME==vid_oe1_lmb_bram_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_mdm_1_0/vid_oe1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_mdm_1_0 || ORIG_REF_NAME==vid_oe1_mdm_1_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_xbar_0/vid_oe1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_xbar_0 || ORIG_REF_NAME==vid_oe1_xbar_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_microblaze_0_axi_periph_0/vid_oe1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==vid_oe1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_v_tc_0_0/vid_oe1_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_v_tc_0_0 || ORIG_REF_NAME==vid_oe1_v_tc_0_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_axi_uartlite_0_0/vid_oe1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_axi_uartlite_0_0 || ORIG_REF_NAME==vid_oe1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_xlconstant_0_0/vid_oe1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_xlconstant_0_0 || ORIG_REF_NAME==vid_oe1_xlconstant_0_0} -quiet] -quiet

# IP: bd/vid_oe1/ip/vid_oe1_xlconstant_0_1/vid_oe1_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe1_xlconstant_0_1 || ORIG_REF_NAME==vid_oe1_xlconstant_0_1} -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE1/VID_OE1.gen/sources_1/bd/vid_oe1/vid_oe1_ooc.xdc
