# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sean/Downloads/git/ECE385_FP/tetris_logic1/tetris_logic1.srcs/sources_1/ip/bg_rom/bg_rom.xci
# IP: The module: 'bg_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sean/Downloads/git/ECE385_FP/tetris_logic1/tetris_logic1.gen/sources_1/ip/bg_rom/bg_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bg_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/sean/Downloads/git/ECE385_FP/tetris_logic1/tetris_logic1.srcs/sources_1/ip/bg_rom/bg_rom.xci
# IP: The module: 'bg_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sean/Downloads/git/ECE385_FP/tetris_logic1/tetris_logic1.gen/sources_1/ip/bg_rom/bg_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bg_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
