# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sean/Downloads/git/ECE385_FP/VID_OE1/VID_OE1.srcs/sources_1/bd/vid_oe1/ip/vid_oe1_axi_vdma_0_0/vid_oe1_axi_vdma_0_0.xci
# IP: The module: 'vid_oe1_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE1/VID_OE1.gen/sources_1/bd/vid_oe1/ip/vid_oe1_axi_vdma_0_0/vid_oe1_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE1/VID_OE1.gen/sources_1/bd/vid_oe1/ip/vid_oe1_axi_vdma_0_0/vid_oe1_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE1/VID_OE1.gen/sources_1/bd/vid_oe1/ip/vid_oe1_axi_vdma_0_0/vid_oe1_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/sean/Downloads/git/ECE385_FP/VID_OE1/VID_OE1.srcs/sources_1/bd/vid_oe1/ip/vid_oe1_axi_vdma_0_0/vid_oe1_axi_vdma_0_0.xci
# IP: The module: 'vid_oe1_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE1/VID_OE1.gen/sources_1/bd/vid_oe1/ip/vid_oe1_axi_vdma_0_0/vid_oe1_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE1/VID_OE1.gen/sources_1/bd/vid_oe1/ip/vid_oe1_axi_vdma_0_0/vid_oe1_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE1/VID_OE1.gen/sources_1/bd/vid_oe1/ip/vid_oe1_axi_vdma_0_0/vid_oe1_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
