##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue Dec  3 17:01:04 2024

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       SPARTAN7
##                    FPGA Part:         XC7S50-CSGA324
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         333.32999999999998 MHz
##                    Time Period:       3000 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K64M16XX-125
## Data Width: 8
## Time Period: 3000
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################

##################################################################################################
## The selected data width is not a multiple of 16. Please note that MIG wizard is not taking care 
## of the 8 floating pins left on the external memory device.
##################################################################################################


set_property INTERNAL_VREF  0.675 [get_iobanks 34]