# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/sjasi3/ECE385/ECE385_FP/DDR3_RE2/DDR3_RE2.srcs/sources_1/bd/ddr3_re2/ip/ddr3_re2_auto_pc_3/ddr3_re2_auto_pc_3.xci
# IP: The module: 'ddr3_re2_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sjasi3/ECE385/ECE385_FP/DDR3_RE2/DDR3_RE2.gen/sources_1/bd/ddr3_re2/ip/ddr3_re2_auto_pc_3/ddr3_re2_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_re2_auto_pc_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/sjasi3/ECE385/ECE385_FP/DDR3_RE2/DDR3_RE2.srcs/sources_1/bd/ddr3_re2/ip/ddr3_re2_auto_pc_3/ddr3_re2_auto_pc_3.xci
# IP: The module: 'ddr3_re2_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sjasi3/ECE385/ECE385_FP/DDR3_RE2/DDR3_RE2.gen/sources_1/bd/ddr3_re2/ip/ddr3_re2_auto_pc_3/ddr3_re2_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_re2_auto_pc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
