# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/DDR3_provided_files/urbana_ddr3.xdc

# Block Designs: bd/ddr3_re2/ddr3_re2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2 || ORIG_REF_NAME==ddr3_re2} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_microblaze_0_0/ddr3_re2_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_microblaze_0_0 || ORIG_REF_NAME==ddr3_re2_microblaze_0_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_mig_7series_0_0/ddr3_re2_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_mig_7series_0_0 || ORIG_REF_NAME==ddr3_re2_mig_7series_0_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_xbar_0/ddr3_re2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_xbar_0 || ORIG_REF_NAME==ddr3_re2_xbar_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_pc_4/ddr3_re2_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_pc_4 || ORIG_REF_NAME==ddr3_re2_auto_pc_4} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_us_0/ddr3_re2_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_us_0 || ORIG_REF_NAME==ddr3_re2_auto_us_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_us_1/ddr3_re2_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_us_1 || ORIG_REF_NAME==ddr3_re2_auto_us_1} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_us_2/ddr3_re2_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_us_2 || ORIG_REF_NAME==ddr3_re2_auto_us_2} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_ds_0/ddr3_re2_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_ds_0 || ORIG_REF_NAME==ddr3_re2_auto_ds_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_pc_0/ddr3_re2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_pc_0 || ORIG_REF_NAME==ddr3_re2_auto_pc_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_ds_1/ddr3_re2_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_ds_1 || ORIG_REF_NAME==ddr3_re2_auto_ds_1} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_pc_1/ddr3_re2_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_pc_1 || ORIG_REF_NAME==ddr3_re2_auto_pc_1} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_ds_2/ddr3_re2_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_ds_2 || ORIG_REF_NAME==ddr3_re2_auto_ds_2} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_pc_2/ddr3_re2_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_pc_2 || ORIG_REF_NAME==ddr3_re2_auto_pc_2} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_ds_3/ddr3_re2_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_ds_3 || ORIG_REF_NAME==ddr3_re2_auto_ds_3} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_auto_pc_3/ddr3_re2_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_auto_pc_3 || ORIG_REF_NAME==ddr3_re2_auto_pc_3} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_microblaze_0_axi_periph_0/ddr3_re2_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ddr3_re2_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_microblaze_0_axi_intc_0/ddr3_re2_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==ddr3_re2_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_microblaze_0_xlconcat_0/ddr3_re2_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_microblaze_0_xlconcat_0 || ORIG_REF_NAME==ddr3_re2_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_mdm_1_0/ddr3_re2_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_mdm_1_0 || ORIG_REF_NAME==ddr3_re2_mdm_1_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_rst_mig_7series_0_197M_0/ddr3_re2_rst_mig_7series_0_197M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_rst_mig_7series_0_197M_0 || ORIG_REF_NAME==ddr3_re2_rst_mig_7series_0_197M_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_axi_timer_0_0/ddr3_re2_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_axi_timer_0_0 || ORIG_REF_NAME==ddr3_re2_axi_timer_0_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_axi_uartlite_0_0/ddr3_re2_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_axi_uartlite_0_0 || ORIG_REF_NAME==ddr3_re2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_axi_gpio_0_0/ddr3_re2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_axi_gpio_0_0 || ORIG_REF_NAME==ddr3_re2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ddr3_re2/ip/ddr3_re2_clk_wiz_0_0/ddr3_re2_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_re2_clk_wiz_0_0 || ORIG_REF_NAME==ddr3_re2_clk_wiz_0_0} -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/DDR3_RE2/DDR3_RE2.gen/sources_1/bd/ddr3_re2/ddr3_re2_ooc.xdc
