-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vid_oe4_v_tpg_0_0_tpgBackground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    bckgndId : IN STD_LOGIC_VECTOR (7 downto 0);
    ZplateHorContStart : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateHorContDelta : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContStart : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContDelta : IN STD_LOGIC_VECTOR (15 downto 0);
    dpDynamicRange : IN STD_LOGIC_VECTOR (7 downto 0);
    dpYUVCoef : IN STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat : IN STD_LOGIC_VECTOR (7 downto 0);
    bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_full_n : IN STD_LOGIC;
    bckgndYUV_write : OUT STD_LOGIC;
    s : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of vid_oe4_v_tpg_0_0_tpgBackground is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_4C : STD_LOGIC_VECTOR (7 downto 0) := "01001100";
    constant ap_const_lv8_95 : STD_LOGIC_VECTOR (7 downto 0) := "10010101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv8_6B : STD_LOGIC_VECTOR (7 downto 0) := "01101011";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv14_F : STD_LOGIC_VECTOR (13 downto 0) := "00000000001111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv14_7 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000111";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal rampStart : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rampVal_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hBarSel : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hdata : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_3 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal rampVal_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hBarSel_1 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal cmp2_i321_fu_629_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp2_i321_reg_1306 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv2_i_i10_i326_fu_635_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i10_i326_reg_1311 : STD_LOGIC_VECTOR (7 downto 0);
    signal not_cmp2_i321_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_cmp2_i321_reg_1316 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv2_i_i10_i331_fu_649_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i10_i331_reg_1321 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i_i333_cast_cast_fu_657_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_i_i_i333_cast_cast_reg_1326 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_i_i10_i349_cast_cast_cast_cast_fu_665_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv2_i_i10_i349_cast_cast_cast_cast_reg_1331 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv2_i_i_i351_fu_673_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i_i351_reg_1336 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_V_fu_681_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_V_reg_1341 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_V_5_fu_689_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_V_5_reg_1346 : STD_LOGIC_VECTOR (7 downto 0);
    signal barWidthMinSamples_fu_721_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal barWidthMinSamples_reg_1351 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_fu_751_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1356 : STD_LOGIC_VECTOR (0 downto 0);
    signal barWidth_reg_1361 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_i_i_i_fu_787_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_i_i_i_reg_1367 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub40_i_fu_793_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub40_i_reg_1372 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1404_fu_799_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1404_reg_1377 : STD_LOGIC_VECTOR (16 downto 0);
    signal cmp59_i_fu_805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp59_i_reg_1382 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp126_i_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp126_i_reg_1387 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp141_i_fu_817_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp141_i_reg_1392 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampStart_load_reg_1397 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln214_fu_899_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln214_reg_1403 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_907_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_reg_1408 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1217_fu_915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1217_reg_1413 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_3_reg_1418 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal cmp12_i_fu_1005_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp12_i_reg_1426 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln518_fu_994_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1404_fu_1022_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1404_reg_1431 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1404_1_fu_1033_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1404_1_reg_1436 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1488_fu_1039_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1488_reg_1441 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln1592_fu_1057_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_reg_1446 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_1_fu_1070_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_1_reg_1451 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_2_fu_1077_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_2_reg_1456 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_idle : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_ready : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_write : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1_ap_vld : STD_LOGIC;
    signal ap_phi_mux_rampVal_3_flag_0_phi_fu_410_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_3_flag_0_reg_406 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_phi_mux_hdata_flag_0_phi_fu_422_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal hdata_flag_0_reg_418 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rampVal_2_flag_0_phi_fu_434_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_2_flag_0_reg_430 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal rampVal_3_new_0_fu_324 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_3_loc_0_fu_320 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_loc_0_fu_316 : STD_LOGIC_VECTOR (15 downto 0);
    signal hBarSel_4_loc_0_fu_312 : STD_LOGIC_VECTOR (7 downto 0);
    signal zonePlateVAddr_loc_0_fu_308 : STD_LOGIC_VECTOR (15 downto 0);
    signal vBarSel_loc_0_fu_304 : STD_LOGIC_VECTOR (7 downto 0);
    signal hBarSel_loc_0_fu_300 : STD_LOGIC_VECTOR (7 downto 0);
    signal hdata_new_0_fu_296 : STD_LOGIC_VECTOR (15 downto 0);
    signal hdata_loc_0_fu_292 : STD_LOGIC_VECTOR (15 downto 0);
    signal vBarSel_2_loc_0_fu_288 : STD_LOGIC_VECTOR (7 downto 0);
    signal hBarSel_3_loc_0_fu_284 : STD_LOGIC_VECTOR (7 downto 0);
    signal rampVal_2_new_0_fu_280 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_2_loc_0_fu_276 : STD_LOGIC_VECTOR (15 downto 0);
    signal vBarSel_3_loc_0_fu_272 : STD_LOGIC_VECTOR (7 downto 0);
    signal hBarSel_5_loc_0_fu_268 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_2_0_0_0558_lcssa567_fu_260 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0556_lcssa564_fu_256 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0554_lcssa561_fu_252 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln705_fu_1089_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_fu_264 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln518_fu_999_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln518_fu_895_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1730_fu_887_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1610_fu_875_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1493_fu_859_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1367_fu_851_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1212_fu_835_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_fu_701_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add2_i_fu_705_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_cast_fu_711_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_72_fu_731_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_741_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_i_fu_757_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add5_i_fu_735_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_2_fu_773_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal barHeight_cast_cast_fu_783_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal loopWidth_cast15_fu_697_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal loopHeight_cast16_fu_727_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln1404_fu_1029_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln518_fu_990_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal Sel_fu_1012_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1592_fu_1045_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1592_1_fu_1051_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1592_2_fu_1064_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vid_oe4_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_full_n : IN STD_LOGIC;
        bckgndYUV_write : OUT STD_LOGIC;
        rampVal_3_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
        pix_val_V_5 : IN STD_LOGIC_VECTOR (7 downto 0);
        pix_val_V : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i_i351 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i_i333_cast_cast : IN STD_LOGIC_VECTOR (4 downto 0);
        conv2_i_i_i_cast : IN STD_LOGIC_VECTOR (0 downto 0);
        select_ln214 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i10_i349_cast_cast_cast_cast : IN STD_LOGIC_VECTOR (2 downto 0);
        conv2_i_i10_i331 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i10_i326 : IN STD_LOGIC_VECTOR (7 downto 0);
        rampStart_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        Zplate_Hor_Control_Start : IN STD_LOGIC_VECTOR (15 downto 0);
        bckgndId_load : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp2_i321 : IN STD_LOGIC_VECTOR (0 downto 0);
        zext_ln1032 : IN STD_LOGIC_VECTOR (7 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        colorFormatLocal : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp141_i : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp_ln1217 : IN STD_LOGIC_VECTOR (0 downto 0);
        barWidth_cast : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidth : IN STD_LOGIC_VECTOR (10 downto 0);
        shl_ln : IN STD_LOGIC_VECTOR (15 downto 0);
        Zplate_Hor_Control_Delta : IN STD_LOGIC_VECTOR (15 downto 0);
        Zplate_Ver_Control_Start : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp12_i : IN STD_LOGIC_VECTOR (0 downto 0);
        Zplate_Ver_Control_Delta : IN STD_LOGIC_VECTOR (15 downto 0);
        sub_i_i_i : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidthMinSamples : IN STD_LOGIC_VECTOR (9 downto 0);
        icmp_ln1404_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp_ln1404 : IN STD_LOGIC_VECTOR (0 downto 0);
        sub40_i : IN STD_LOGIC_VECTOR (16 downto 0);
        add_ln1488 : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp35_i526 : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln1592 : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln1592_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln1592_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp59_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp126_i : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_4_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        zonePlateVAddr_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hdata_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_1_out_ap_vld : OUT STD_LOGIC;
        hdata_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_new_1_out_ap_vld : OUT STD_LOGIC;
        hdata_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_2_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_3_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_2_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_3_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_5_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_0557_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0557_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0557_out_o_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_0555_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0555_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0555_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0553_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0553_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0553_out_o_ap_vld : OUT STD_LOGIC;
        rampVal : OUT STD_LOGIC_VECTOR (7 downto 0);
        rampVal_ap_vld : OUT STD_LOGIC;
        hBarSel_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_2_ap_vld : OUT STD_LOGIC;
        s : IN STD_LOGIC_VECTOR (31 downto 0);
        zonePlateVAddr : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_ap_vld : OUT STD_LOGIC;
        hBarSel : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_ap_vld : OUT STD_LOGIC;
        vBarSel : OUT STD_LOGIC_VECTOR (2 downto 0);
        vBarSel_ap_vld : OUT STD_LOGIC;
        hBarSel_3 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_3_ap_vld : OUT STD_LOGIC;
        vBarSel_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_ap_vld : OUT STD_LOGIC;
        hBarSel_1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_1_ap_vld : OUT STD_LOGIC;
        vBarSel_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        vBarSel_1_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442 : component vid_oe4_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start,
        ap_done => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done,
        ap_idle => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_idle,
        ap_ready => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_ready,
        bckgndYUV_din => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_din,
        bckgndYUV_num_data_valid => ap_const_lv5_0,
        bckgndYUV_fifo_cap => ap_const_lv5_0,
        bckgndYUV_full_n => bckgndYUV_full_n,
        bckgndYUV_write => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_write,
        rampVal_3_flag_0 => rampVal_3_flag_0_reg_406,
        hdata_flag_0 => hdata_flag_0_reg_418,
        rampVal_2_flag_0 => rampVal_2_flag_0_reg_430,
        loopWidth => width,
        pix_val_V_5 => pix_val_V_5_reg_1346,
        pix_val_V => pix_val_V_reg_1341,
        conv2_i_i_i351 => conv2_i_i_i351_reg_1336,
        conv2_i_i_i333_cast_cast => conv2_i_i_i333_cast_cast_reg_1326,
        conv2_i_i_i_cast => not_cmp2_i321_reg_1316,
        select_ln214 => select_ln214_reg_1403,
        conv2_i_i10_i349_cast_cast_cast_cast => conv2_i_i10_i349_cast_cast_cast_cast_reg_1331,
        conv2_i_i10_i331 => conv2_i_i10_i331_reg_1321,
        conv2_i_i10_i326 => conv2_i_i10_i326_reg_1311,
        rampStart_1 => rampStart_load_reg_1397,
        Zplate_Hor_Control_Start => ZplateHorContStart,
        bckgndId_load => bckgndId,
        cmp2_i321 => cmp2_i321_reg_1306,
        zext_ln1032 => rampStart_load_reg_1397,
        y => y_3_reg_1418,
        colorFormatLocal => colorFormat,
        cmp141_i => cmp141_i_reg_1392,
        icmp_ln1217 => icmp_ln1217_reg_1413,
        barWidth_cast => barWidth_reg_1361,
        barWidth => barWidth_reg_1361,
        shl_ln => shl_ln_reg_1408,
        Zplate_Hor_Control_Delta => ZplateHorContDelta,
        Zplate_Ver_Control_Start => ZplateVerContStart,
        cmp12_i => cmp12_i_reg_1426,
        Zplate_Ver_Control_Delta => ZplateVerContDelta,
        sub_i_i_i => sub_i_i_i_reg_1367,
        barWidthMinSamples => barWidthMinSamples_reg_1351,
        icmp_ln1404_1 => icmp_ln1404_1_reg_1436,
        icmp_ln1404 => icmp_ln1404_reg_1431,
        sub40_i => sub40_i_reg_1372,
        add_ln1488 => add_ln1488_reg_1441,
        cmp35_i526 => icmp_reg_1356,
        or_ln1592 => or_ln1592_reg_1446,
        or_ln1592_1 => or_ln1592_1_reg_1451,
        or_ln1592_2 => or_ln1592_2_reg_1456,
        cmp59_i => cmp59_i_reg_1382,
        cmp126_i => cmp126_i_reg_1387,
        rampVal_3_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out,
        rampVal_3_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out_ap_vld,
        rampVal_3_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out,
        rampVal_3_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out_ap_vld,
        rampVal_3_loc_1_out_i => rampVal_3_loc_0_fu_320,
        rampVal_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o,
        rampVal_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o_ap_vld,
        rampVal_loc_1_out_i => rampVal_loc_0_fu_316,
        rampVal_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o,
        rampVal_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o_ap_vld,
        hBarSel_4_loc_1_out_i => hBarSel_4_loc_0_fu_312,
        hBarSel_4_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o,
        hBarSel_4_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o_ap_vld,
        zonePlateVAddr_loc_1_out_i => zonePlateVAddr_loc_0_fu_308,
        zonePlateVAddr_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o,
        zonePlateVAddr_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o_ap_vld,
        vBarSel_loc_1_out_i => vBarSel_loc_0_fu_304,
        vBarSel_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o,
        vBarSel_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o_ap_vld,
        hBarSel_loc_1_out_i => hBarSel_loc_0_fu_300,
        hBarSel_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o,
        hBarSel_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o_ap_vld,
        hdata_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out,
        hdata_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out_ap_vld,
        hdata_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out,
        hdata_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out_ap_vld,
        hdata_loc_1_out_i => hdata_loc_0_fu_292,
        hdata_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o,
        hdata_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o_ap_vld,
        vBarSel_2_loc_1_out_i => vBarSel_2_loc_0_fu_288,
        vBarSel_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o,
        vBarSel_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o_ap_vld,
        hBarSel_3_loc_1_out_i => hBarSel_3_loc_0_fu_284,
        hBarSel_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o,
        hBarSel_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o_ap_vld,
        rampVal_2_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out,
        rampVal_2_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out_ap_vld,
        rampVal_2_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out,
        rampVal_2_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out_ap_vld,
        rampVal_2_loc_1_out_i => rampVal_2_loc_0_fu_276,
        rampVal_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o,
        rampVal_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o_ap_vld,
        vBarSel_3_loc_1_out_i => vBarSel_3_loc_0_fu_272,
        vBarSel_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o,
        vBarSel_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o_ap_vld,
        hBarSel_5_loc_1_out_i => hBarSel_5_loc_0_fu_268,
        hBarSel_5_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o,
        hBarSel_5_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o_ap_vld,
        p_0_2_0_0_0557_out_i => p_0_2_0_0_0558_lcssa567_fu_260,
        p_0_2_0_0_0557_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o,
        p_0_2_0_0_0557_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o_ap_vld,
        p_0_1_0_0_0555_out_i => p_0_1_0_0_0556_lcssa564_fu_256,
        p_0_1_0_0_0555_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o,
        p_0_1_0_0_0555_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o_ap_vld,
        p_0_0_0_0_0553_out_i => p_0_0_0_0_0554_lcssa561_fu_252,
        p_0_0_0_0_0553_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o,
        p_0_0_0_0_0553_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o_ap_vld,
        rampVal => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal,
        rampVal_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_ap_vld,
        hBarSel_2 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2,
        hBarSel_2_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2_ap_vld,
        s => s,
        zonePlateVAddr => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr,
        zonePlateVAddr_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_ap_vld,
        hBarSel => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel,
        hBarSel_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_ap_vld,
        vBarSel => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel,
        vBarSel_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_ap_vld,
        hBarSel_3 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3,
        hBarSel_3_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_ap_vld,
        vBarSel_2 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2,
        vBarSel_2_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_ap_vld,
        hBarSel_1 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1,
        hBarSel_1_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_ap_vld,
        vBarSel_1 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1,
        vBarSel_1_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_994_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_994_p2 = ap_const_lv1_0))) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_ready = ap_const_logic_1)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    hBarSel_3_loc_0_fu_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_3_loc_0_fu_284 <= zext_ln1610_fu_875_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hBarSel_3_loc_0_fu_284 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_4_loc_0_fu_312_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_4_loc_0_fu_312 <= hBarSel_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hBarSel_4_loc_0_fu_312 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_4_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_5_loc_0_fu_268_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_5_loc_0_fu_268 <= zext_ln518_fu_895_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hBarSel_5_loc_0_fu_268 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_5_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_loc_0_fu_300_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_loc_0_fu_300 <= zext_ln1493_fu_859_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hBarSel_loc_0_fu_300 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_loc_1_out_o;
            end if; 
        end if;
    end process;

    hdata_flag_0_reg_418_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                hdata_flag_0_reg_418 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_flag_0_reg_418 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    hdata_loc_0_fu_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_loc_0_fu_292 <= hdata;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hdata_loc_0_fu_292 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_2_flag_0_reg_430_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                rampVal_2_flag_0_reg_430 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_flag_0_reg_430 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_2_loc_0_fu_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_loc_0_fu_276 <= rampVal_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                rampVal_2_loc_0_fu_276 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_3_flag_0_reg_406_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                rampVal_3_flag_0_reg_406 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_flag_0_reg_406 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_3_loc_0_fu_320_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_loc_0_fu_320 <= rampVal_1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                rampVal_3_loc_0_fu_320 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_loc_0_fu_316_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_loc_0_fu_316 <= zext_ln1212_fu_835_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                rampVal_loc_0_fu_316 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_2_loc_0_fu_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_2_loc_0_fu_288 <= vBarSel_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                vBarSel_2_loc_0_fu_288 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_3_loc_0_fu_272_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_3_loc_0_fu_272 <= zext_ln1730_fu_887_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                vBarSel_3_loc_0_fu_272 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_loc_0_fu_304_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_loc_0_fu_304 <= zext_ln1367_fu_851_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                vBarSel_loc_0_fu_304 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_loc_1_out_o;
            end if; 
        end if;
    end process;

    y_fu_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_264 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_994_p2 = ap_const_lv1_0))) then 
                y_fu_264 <= add_ln518_fu_999_p2;
            end if; 
        end if;
    end process;

    zonePlateVAddr_loc_0_fu_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                zonePlateVAddr_loc_0_fu_308 <= zonePlateVAddr;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                zonePlateVAddr_loc_0_fu_308 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln1404_reg_1377 <= add_ln1404_fu_799_p2;
                barWidthMinSamples_reg_1351 <= barWidthMinSamples_fu_721_p2;
                barWidth_reg_1361 <= add_i_fu_757_p2(13 downto 3);
                cmp126_i_reg_1387 <= cmp126_i_fu_811_p2;
                cmp141_i_reg_1392 <= cmp141_i_fu_817_p2;
                cmp2_i321_reg_1306 <= cmp2_i321_fu_629_p2;
                cmp59_i_reg_1382 <= cmp59_i_fu_805_p2;
                    conv2_i_i10_i326_reg_1311(1 downto 0) <= conv2_i_i10_i326_fu_635_p3(1 downto 0);    conv2_i_i10_i326_reg_1311(5 downto 4) <= conv2_i_i10_i326_fu_635_p3(5 downto 4);    conv2_i_i10_i326_reg_1311(7) <= conv2_i_i10_i326_fu_635_p3(7);
                    conv2_i_i10_i331_reg_1321(0) <= conv2_i_i10_i331_fu_649_p3(0);    conv2_i_i10_i331_reg_1321(2) <= conv2_i_i10_i331_fu_649_p3(2);    conv2_i_i10_i331_reg_1321(4) <= conv2_i_i10_i331_fu_649_p3(4);    conv2_i_i10_i331_reg_1321(7) <= conv2_i_i10_i331_fu_649_p3(7);
                    conv2_i_i10_i349_cast_cast_cast_cast_reg_1331(0) <= conv2_i_i10_i349_cast_cast_cast_cast_fu_665_p3(0);    conv2_i_i10_i349_cast_cast_cast_cast_reg_1331(2) <= conv2_i_i10_i349_cast_cast_cast_cast_fu_665_p3(2);
                    conv2_i_i_i333_cast_cast_reg_1326(0) <= conv2_i_i_i333_cast_cast_fu_657_p3(0);    conv2_i_i_i333_cast_cast_reg_1326(2) <= conv2_i_i_i333_cast_cast_fu_657_p3(2);    conv2_i_i_i333_cast_cast_reg_1326(4) <= conv2_i_i_i333_cast_cast_fu_657_p3(4);
                    conv2_i_i_i351_reg_1336(2) <= conv2_i_i_i351_fu_673_p3(2);    conv2_i_i_i351_reg_1336(4) <= conv2_i_i_i351_fu_673_p3(4);    conv2_i_i_i351_reg_1336(7) <= conv2_i_i_i351_fu_673_p3(7);
                icmp_ln1217_reg_1413 <= icmp_ln1217_fu_915_p2;
                icmp_reg_1356 <= icmp_fu_751_p2;
                not_cmp2_i321_reg_1316 <= not_cmp2_i321_fu_643_p2;
                    pix_val_V_5_reg_1346(6 downto 0) <= pix_val_V_5_fu_689_p3(6 downto 0);
                    pix_val_V_reg_1341(7) <= pix_val_V_fu_681_p3(7);
                rampStart_load_reg_1397 <= rampStart;
                select_ln214_reg_1403 <= select_ln214_fu_899_p3;
                    shl_ln_reg_1408(15 downto 8) <= shl_ln_fu_907_p3(15 downto 8);
                sub40_i_reg_1372 <= sub40_i_fu_793_p2;
                sub_i_i_i_reg_1367 <= sub_i_i_i_fu_787_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_994_p2 = ap_const_lv1_0))) then
                add_ln1488_reg_1441 <= add_ln1488_fu_1039_p2;
                cmp12_i_reg_1426 <= cmp12_i_fu_1005_p2;
                icmp_ln1404_1_reg_1436 <= icmp_ln1404_1_fu_1033_p2;
                icmp_ln1404_reg_1431 <= icmp_ln1404_fu_1022_p2;
                or_ln1592_1_reg_1451 <= or_ln1592_1_fu_1070_p2;
                or_ln1592_2_reg_1456 <= or_ln1592_2_fu_1077_p2;
                or_ln1592_reg_1446 <= or_ln1592_fu_1057_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hBarSel_3 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_hdata_flag_0_phi_fu_422_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_994_p2 = ap_const_lv1_1))) then
                hdata <= hdata_new_0_fu_296;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hdata_new_0_fu_296 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                p_0_0_0_0_0554_lcssa561_fu_252 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0553_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                p_0_1_0_0_0556_lcssa564_fu_256 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0555_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                p_0_2_0_0_0558_lcssa567_fu_260 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0557_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_994_p2 = ap_const_lv1_1))) then
                rampStart <= add_ln705_fu_1089_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_rampVal_3_flag_0_phi_fu_410_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_994_p2 = ap_const_lv1_1))) then
                rampVal_1 <= rampVal_3_new_0_fu_324;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_rampVal_2_flag_0_phi_fu_434_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_994_p2 = ap_const_lv1_1))) then
                rampVal_2 <= rampVal_2_new_0_fu_280;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                rampVal_2_new_0_fu_280 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                rampVal_3_new_0_fu_324 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_vBarSel_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                y_3_reg_1418 <= y_fu_264;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr;
            end if;
        end if;
    end process;
    conv2_i_i10_i326_reg_1311(3 downto 2) <= "11";
    conv2_i_i10_i326_reg_1311(6) <= '1';
    conv2_i_i10_i331_reg_1321(1) <= '0';
    conv2_i_i10_i331_reg_1321(3 downto 3) <= "0";
    conv2_i_i10_i331_reg_1321(6 downto 5) <= "00";
    conv2_i_i_i333_cast_cast_reg_1326(1) <= '0';
    conv2_i_i_i333_cast_cast_reg_1326(3) <= '0';
    conv2_i_i10_i349_cast_cast_cast_cast_reg_1331(1) <= '0';
    conv2_i_i_i351_reg_1336(1 downto 0) <= "11";
    conv2_i_i_i351_reg_1336(3 downto 3) <= "1";
    conv2_i_i_i351_reg_1336(6 downto 5) <= "11";
    pix_val_V_reg_1341(6 downto 0) <= "0000000";
    pix_val_V_5_reg_1346(7) <= '1';
    shl_ln_reg_1408(7 downto 0) <= "00000000";

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln518_fu_994_p2, grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_994_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    Sel_fu_1012_p4 <= y_fu_264(7 downto 6);
    add2_i_fu_705_p2 <= std_logic_vector(unsigned(empty_fu_701_p1) + unsigned(ap_const_lv14_F));
    add5_i_fu_735_p2 <= std_logic_vector(unsigned(empty_72_fu_731_p1) + unsigned(ap_const_lv14_F));
    add_i_fu_757_p2 <= std_logic_vector(unsigned(empty_fu_701_p1) + unsigned(ap_const_lv14_7));
    add_ln1404_fu_799_p2 <= std_logic_vector(unsigned(loopHeight_cast16_fu_727_p1) + unsigned(ap_const_lv17_1FFFF));
    add_ln1488_fu_1039_p2 <= std_logic_vector(unsigned(rampStart) + unsigned(trunc_ln518_fu_990_p1));
    add_ln518_fu_999_p2 <= std_logic_vector(unsigned(y_fu_264) + unsigned(ap_const_lv16_1));
    add_ln705_fu_1089_p2 <= std_logic_vector(unsigned(motionSpeed) + unsigned(rampStart));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done)
    begin
        if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln518_fu_994_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_994_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_hdata_flag_0_phi_fu_422_p4 <= hdata_flag_0_reg_418;
    ap_phi_mux_rampVal_2_flag_0_phi_fu_434_p4 <= rampVal_2_flag_0_reg_430;
    ap_phi_mux_rampVal_3_flag_0_phi_fu_410_p4 <= rampVal_3_flag_0_reg_406;
    ap_ready <= internal_ap_ready;
    barHeight_cast_cast_fu_783_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_773_p4),11));
    barWidthMinSamples_fu_721_p2 <= std_logic_vector(unsigned(p_cast_fu_711_p4) + unsigned(ap_const_lv10_3FF));
    bckgndYUV_din <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_din;

    bckgndYUV_write_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            bckgndYUV_write <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_write;
        else 
            bckgndYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp126_i_fu_811_p2 <= "1" when (dpYUVCoef = ap_const_lv8_0) else "0";
    cmp12_i_fu_1005_p2 <= "0" when (y_fu_264 = ap_const_lv16_0) else "1";
    cmp141_i_fu_817_p2 <= "0" when (colorFormat = ap_const_lv8_1) else "1";
    cmp2_i321_fu_629_p2 <= "1" when (colorFormat = ap_const_lv8_0) else "0";
    cmp59_i_fu_805_p2 <= "1" when (dpDynamicRange = ap_const_lv8_0) else "0";
    conv2_i_i10_i326_fu_635_p3 <= 
        ap_const_lv8_FF when (cmp2_i321_fu_629_p2(0) = '1') else 
        ap_const_lv8_4C;
    conv2_i_i10_i331_fu_649_p3 <= 
        ap_const_lv8_0 when (cmp2_i321_fu_629_p2(0) = '1') else 
        ap_const_lv8_95;
    conv2_i_i10_i349_cast_cast_cast_cast_fu_665_p3 <= 
        ap_const_lv3_0 when (cmp2_i321_fu_629_p2(0) = '1') else 
        ap_const_lv3_5;
    conv2_i_i_i333_cast_cast_fu_657_p3 <= 
        ap_const_lv5_0 when (cmp2_i321_fu_629_p2(0) = '1') else 
        ap_const_lv5_15;
    conv2_i_i_i351_fu_673_p3 <= 
        ap_const_lv8_FF when (cmp2_i321_fu_629_p2(0) = '1') else 
        ap_const_lv8_6B;
    empty_72_fu_731_p1 <= height(14 - 1 downto 0);
    empty_fu_701_p1 <= width(14 - 1 downto 0);
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg;
    icmp_fu_751_p2 <= "0" when (tmp_fu_741_p4 = ap_const_lv7_0) else "1";
    icmp_ln1217_fu_915_p2 <= "0" when (colorFormat = ap_const_lv8_0) else "1";
    icmp_ln1404_1_fu_1033_p2 <= "1" when (add_ln1404_reg_1377 = zext_ln1404_fu_1029_p1) else "0";
    icmp_ln1404_fu_1022_p2 <= "1" when (y_fu_264 = ap_const_lv16_0) else "0";
    icmp_ln1592_1_fu_1051_p2 <= "1" when (Sel_fu_1012_p4 = ap_const_lv2_2) else "0";
    icmp_ln1592_2_fu_1064_p2 <= "1" when (Sel_fu_1012_p4 = ap_const_lv2_0) else "0";
    icmp_ln1592_fu_1045_p2 <= "1" when (Sel_fu_1012_p4 = ap_const_lv2_1) else "0";
    icmp_ln518_fu_994_p2 <= "1" when (y_fu_264 = height) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln518_fu_994_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_994_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    loopHeight_cast16_fu_727_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),17));
    loopWidth_cast15_fu_697_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),17));
    not_cmp2_i321_fu_643_p2 <= (cmp2_i321_fu_629_p2 xor ap_const_lv1_1);
    or_ln1592_1_fu_1070_p2 <= (icmp_ln1592_2_fu_1064_p2 or icmp_ln1592_1_fu_1051_p2);
    or_ln1592_2_fu_1077_p2 <= (icmp_ln1592_fu_1045_p2 or icmp_ln1592_2_fu_1064_p2);
    or_ln1592_fu_1057_p2 <= (icmp_ln1592_fu_1045_p2 or icmp_ln1592_1_fu_1051_p2);
    p_cast_fu_711_p4 <= add2_i_fu_705_p2(13 downto 4);
    pix_val_V_5_fu_689_p3 <= 
        ap_const_lv8_FF when (cmp2_i321_fu_629_p2(0) = '1') else 
        ap_const_lv8_80;
    pix_val_V_fu_681_p3 <= 
        ap_const_lv8_0 when (cmp2_i321_fu_629_p2(0) = '1') else 
        ap_const_lv8_80;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln214_fu_899_p3 <= 
        rampStart when (cmp2_i321_fu_629_p2(0) = '1') else 
        ap_const_lv8_80;
    shl_ln_fu_907_p3 <= (rampStart & ap_const_lv8_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub40_i_fu_793_p2 <= std_logic_vector(unsigned(loopWidth_cast15_fu_697_p1) + unsigned(ap_const_lv17_1FFFF));
    sub_i_i_i_fu_787_p2 <= std_logic_vector(unsigned(barHeight_cast_cast_fu_783_p1) + unsigned(ap_const_lv11_7FF));
    tmp_2_fu_773_p4 <= add5_i_fu_735_p2(13 downto 4);
    tmp_fu_741_p4 <= colorFormat(7 downto 1);
    trunc_ln518_fu_990_p1 <= y_fu_264(8 - 1 downto 0);
    zext_ln1212_fu_835_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rampVal),16));
    zext_ln1367_fu_851_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel),8));
    zext_ln1404_fu_1029_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_264),17));
    zext_ln1493_fu_859_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel),8));
    zext_ln1610_fu_875_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_3),8));
    zext_ln1730_fu_887_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel_1),8));
    zext_ln518_fu_895_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_1),8));
end behav;
