# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/DDR3_provided_files/urbana_ddr3.xdc

# Block Designs: bd/vid_oe3/vid_oe3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3 || ORIG_REF_NAME==vid_oe3} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_mig_7series_0_0/vid_oe3_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_mig_7series_0_0 || ORIG_REF_NAME==vid_oe3_mig_7series_0_0} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_microblaze_0_0/vid_oe3_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_microblaze_0_0 || ORIG_REF_NAME==vid_oe3_microblaze_0_0} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_xbar_1/vid_oe3_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_xbar_1 || ORIG_REF_NAME==vid_oe3_xbar_1} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_microblaze_0_axi_periph_1/vid_oe3_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_microblaze_0_axi_periph_1 || ORIG_REF_NAME==vid_oe3_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_microblaze_0_axi_intc_1/vid_oe3_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_microblaze_0_axi_intc_1 || ORIG_REF_NAME==vid_oe3_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_microblaze_0_xlconcat_1/vid_oe3_microblaze_0_xlconcat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_microblaze_0_xlconcat_1 || ORIG_REF_NAME==vid_oe3_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_mdm_1_1/vid_oe3_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_mdm_1_1 || ORIG_REF_NAME==vid_oe3_mdm_1_1} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_rst_mig_7series_0_83M_1/vid_oe3_rst_mig_7series_0_83M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_rst_mig_7series_0_83M_1 || ORIG_REF_NAME==vid_oe3_rst_mig_7series_0_83M_1} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_axi_uartlite_0_1/vid_oe3_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_axi_uartlite_0_1 || ORIG_REF_NAME==vid_oe3_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_axi_timer_0_0/vid_oe3_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_axi_timer_0_0 || ORIG_REF_NAME==vid_oe3_axi_timer_0_0} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_rgb2dvi_0_0/vid_oe3_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_rgb2dvi_0_0 || ORIG_REF_NAME==vid_oe3_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_clk_wiz_0_0/vid_oe3_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_clk_wiz_0_0 || ORIG_REF_NAME==vid_oe3_clk_wiz_0_0} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_v_axi4s_vid_out_0_0/vid_oe3_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==vid_oe3_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_v_tpg_0_0/vid_oe3_v_tpg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_v_tpg_0_0 || ORIG_REF_NAME==vid_oe3_v_tpg_0_0} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_v_tc_0_0/vid_oe3_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_v_tc_0_0 || ORIG_REF_NAME==vid_oe3_v_tc_0_0} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_pc_5/vid_oe3_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_pc_5 || ORIG_REF_NAME==vid_oe3_auto_pc_5} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_us_0/vid_oe3_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_us_0 || ORIG_REF_NAME==vid_oe3_auto_us_0} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_us_1/vid_oe3_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_us_1 || ORIG_REF_NAME==vid_oe3_auto_us_1} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_us_2/vid_oe3_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_us_2 || ORIG_REF_NAME==vid_oe3_auto_us_2} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_ds_0/vid_oe3_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_ds_0 || ORIG_REF_NAME==vid_oe3_auto_ds_0} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_pc_0/vid_oe3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_pc_0 || ORIG_REF_NAME==vid_oe3_auto_pc_0} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_ds_1/vid_oe3_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_ds_1 || ORIG_REF_NAME==vid_oe3_auto_ds_1} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_pc_1/vid_oe3_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_pc_1 || ORIG_REF_NAME==vid_oe3_auto_pc_1} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_ds_2/vid_oe3_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_ds_2 || ORIG_REF_NAME==vid_oe3_auto_ds_2} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_pc_2/vid_oe3_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_pc_2 || ORIG_REF_NAME==vid_oe3_auto_pc_2} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_ds_3/vid_oe3_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_ds_3 || ORIG_REF_NAME==vid_oe3_auto_ds_3} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_pc_3/vid_oe3_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_pc_3 || ORIG_REF_NAME==vid_oe3_auto_pc_3} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_ds_4/vid_oe3_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_ds_4 || ORIG_REF_NAME==vid_oe3_auto_ds_4} -quiet] -quiet

# IP: bd/vid_oe3/ip/vid_oe3_auto_pc_4/vid_oe3_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe3_auto_pc_4 || ORIG_REF_NAME==vid_oe3_auto_pc_4} -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE3/VID_OE3.gen/sources_1/bd/vid_oe3/vid_oe3_ooc.xdc
