##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Thu Nov 14 22:42:58 2024

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       SPARTAN7
##                    FPGA Part:         XC7S50-CSGA324
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         333.32999999999998 MHz
##                    Time Period:       3000 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K64M16XX-125
## Data Width: 16
## Time Period: 3000
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################


# PadFunction: IO_L6P_T0_15 
set_property IOSTANDARD LVCMOS25 [get_ports {tg_compare_error}]
set_property PACKAGE_PIN C13 [get_ports {tg_compare_error}]


set_property INTERNAL_VREF  0.675 [get_iobanks 34]