# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/DDR3_provided_files/urbana_ddr3.xdc

# Block Designs: bd/vid_oe4/vid_oe4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4 || ORIG_REF_NAME==vid_oe4} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_mig_7series_0_0/vid_oe4_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_mig_7series_0_0 || ORIG_REF_NAME==vid_oe4_mig_7series_0_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_microblaze_0_0/vid_oe4_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_microblaze_0_0 || ORIG_REF_NAME==vid_oe4_microblaze_0_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_dlmb_v10_0/vid_oe4_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_dlmb_v10_0 || ORIG_REF_NAME==vid_oe4_dlmb_v10_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_ilmb_v10_0/vid_oe4_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_ilmb_v10_0 || ORIG_REF_NAME==vid_oe4_ilmb_v10_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_dlmb_bram_if_cntlr_0/vid_oe4_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==vid_oe4_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_ilmb_bram_if_cntlr_0/vid_oe4_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==vid_oe4_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_lmb_bram_0/vid_oe4_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_lmb_bram_0 || ORIG_REF_NAME==vid_oe4_lmb_bram_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_xbar_0/vid_oe4_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_xbar_0 || ORIG_REF_NAME==vid_oe4_xbar_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_microblaze_0_axi_periph_0/vid_oe4_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_microblaze_0_axi_periph_0 || ORIG_REF_NAME==vid_oe4_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_microblaze_0_axi_intc_0/vid_oe4_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_microblaze_0_axi_intc_0 || ORIG_REF_NAME==vid_oe4_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_microblaze_0_xlconcat_0/vid_oe4_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_microblaze_0_xlconcat_0 || ORIG_REF_NAME==vid_oe4_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_mdm_1_0/vid_oe4_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_mdm_1_0 || ORIG_REF_NAME==vid_oe4_mdm_1_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_rst_mig_7series_0_83M_0/vid_oe4_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==vid_oe4_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_axi_uartlite_0_0/vid_oe4_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_axi_uartlite_0_0 || ORIG_REF_NAME==vid_oe4_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_clk_wiz_0_0/vid_oe4_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_clk_wiz_0_0 || ORIG_REF_NAME==vid_oe4_clk_wiz_0_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_v_tc_0_0/vid_oe4_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_v_tc_0_0 || ORIG_REF_NAME==vid_oe4_v_tc_0_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_v_tpg_0_0/vid_oe4_v_tpg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_v_tpg_0_0 || ORIG_REF_NAME==vid_oe4_v_tpg_0_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_v_axi4s_vid_out_0_0/vid_oe4_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==vid_oe4_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_rgb2dvi_0_0/vid_oe4_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_rgb2dvi_0_0 || ORIG_REF_NAME==vid_oe4_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_pc_4/vid_oe4_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_pc_4 || ORIG_REF_NAME==vid_oe4_auto_pc_4} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_us_0/vid_oe4_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_us_0 || ORIG_REF_NAME==vid_oe4_auto_us_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_us_1/vid_oe4_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_us_1 || ORIG_REF_NAME==vid_oe4_auto_us_1} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_us_2/vid_oe4_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_us_2 || ORIG_REF_NAME==vid_oe4_auto_us_2} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_ds_0/vid_oe4_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_ds_0 || ORIG_REF_NAME==vid_oe4_auto_ds_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_pc_0/vid_oe4_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_pc_0 || ORIG_REF_NAME==vid_oe4_auto_pc_0} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_ds_1/vid_oe4_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_ds_1 || ORIG_REF_NAME==vid_oe4_auto_ds_1} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_pc_1/vid_oe4_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_pc_1 || ORIG_REF_NAME==vid_oe4_auto_pc_1} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_ds_2/vid_oe4_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_ds_2 || ORIG_REF_NAME==vid_oe4_auto_ds_2} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_pc_2/vid_oe4_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_pc_2 || ORIG_REF_NAME==vid_oe4_auto_pc_2} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_ds_3/vid_oe4_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_ds_3 || ORIG_REF_NAME==vid_oe4_auto_ds_3} -quiet] -quiet

# IP: bd/vid_oe4/ip/vid_oe4_auto_pc_3/vid_oe4_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_oe4_auto_pc_3 || ORIG_REF_NAME==vid_oe4_auto_pc_3} -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE4/VID_OE4.gen/sources_1/bd/vid_oe4/vid_oe4_ooc.xdc
