# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/sjasi3/ECE385_FP/tetris_logic1/tetris_logic1.srcs/sources_1/ip/start_rom/start_rom.xci
# IP: The module: 'start_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sjasi3/ECE385_FP/tetris_logic1/tetris_logic1.gen/sources_1/ip/start_rom/start_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'start_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/sjasi3/ECE385_FP/tetris_logic1/tetris_logic1.srcs/sources_1/ip/start_rom/start_rom.xci
# IP: The module: 'start_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sjasi3/ECE385_FP/tetris_logic1/tetris_logic1.gen/sources_1/ip/start_rom/start_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'start_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
