# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/sjasi3/ECE385_FP/VID_OE4/VID_OE4.srcs/sources_1/bd/vid_oe4/ip/vid_oe4_auto_ds_4/vid_oe4_auto_ds_4.xci
# IP: The module: 'vid_oe4_auto_ds_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sjasi3/ECE385_FP/VID_OE4/VID_OE4.gen/sources_1/bd/vid_oe4/ip/vid_oe4_auto_ds_4/vid_oe4_auto_ds_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe4_auto_ds_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/sjasi3/ECE385_FP/VID_OE4/VID_OE4.gen/sources_1/bd/vid_oe4/ip/vid_oe4_auto_ds_4/vid_oe4_auto_ds_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe4_auto_ds_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/sjasi3/ECE385_FP/VID_OE4/VID_OE4.srcs/sources_1/bd/vid_oe4/ip/vid_oe4_auto_ds_4/vid_oe4_auto_ds_4.xci
# IP: The module: 'vid_oe4_auto_ds_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sjasi3/ECE385_FP/VID_OE4/VID_OE4.gen/sources_1/bd/vid_oe4/ip/vid_oe4_auto_ds_4/vid_oe4_auto_ds_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe4_auto_ds_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/sjasi3/ECE385_FP/VID_OE4/VID_OE4.gen/sources_1/bd/vid_oe4/ip/vid_oe4_auto_ds_4/vid_oe4_auto_ds_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe4_auto_ds_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
