-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vid_oe1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bckgndYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_empty_n : IN STD_LOGIC;
    bckgndYUV_read : OUT STD_LOGIC;
    ovrlayYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_full_n : IN STD_LOGIC;
    ovrlayYUV_write : OUT STD_LOGIC;
    boxHCoord_loc_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
    pixOut_val_V_9 : IN STD_LOGIC_VECTOR (7 downto 0);
    pixOut_val_V : IN STD_LOGIC_VECTOR (7 downto 0);
    pixOut_val_V_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    and4_i : IN STD_LOGIC_VECTOR (0 downto 0);
    and26_i : IN STD_LOGIC_VECTOR (0 downto 0);
    tobool : IN STD_LOGIC_VECTOR (0 downto 0);
    and10_i : IN STD_LOGIC_VECTOR (0 downto 0);
    ovrlayId_load : IN STD_LOGIC_VECTOR (7 downto 0);
    boxSize_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    y : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln1869 : IN STD_LOGIC_VECTOR (7 downto 0);
    vMax : IN STD_LOGIC_VECTOR (15 downto 0);
    hMax : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln1869_1 : IN STD_LOGIC_VECTOR (8 downto 0);
    cmp101_i : IN STD_LOGIC_VECTOR (0 downto 0);
    boxColorG_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    crossHairX_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    cmp2_i : IN STD_LOGIC_VECTOR (0 downto 0);
    color : IN STD_LOGIC_VECTOR (7 downto 0);
    boxHCoord_loc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_loc_1_out_ap_vld : OUT STD_LOGIC;
    boxVCoord_loc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_1_out_ap_vld : OUT STD_LOGIC;
    boxHCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_ap_vld : OUT STD_LOGIC;
    boxVCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_ap_vld : OUT STD_LOGIC );
end;


architecture behav of vid_oe1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv8_F0 : STD_LOGIC_VECTOR (7 downto 0) := "11110000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln729_reg_909 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln729_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal vDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal whiYuv_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal whiYuv_2_ce0 : STD_LOGIC;
    signal whiYuv_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ovrlayYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal bckgndYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal color_read_reg_779 : STD_LOGIC_VECTOR (7 downto 0);
    signal crossHairX_1_read_reg_788 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxColorG_1_read_reg_793 : STD_LOGIC_VECTOR (7 downto 0);
    signal cmp101_i_read_reg_798 : STD_LOGIC_VECTOR (0 downto 0);
    signal hMax_read_reg_803 : STD_LOGIC_VECTOR (15 downto 0);
    signal vMax_read_reg_808 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxSize_1_read_reg_820 : STD_LOGIC_VECTOR (15 downto 0);
    signal ovrlayId_load_read_reg_826 : STD_LOGIC_VECTOR (7 downto 0);
    signal and10_i_read_reg_830 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool_read_reg_835 : STD_LOGIC_VECTOR (0 downto 0);
    signal and26_i_read_reg_842 : STD_LOGIC_VECTOR (0 downto 0);
    signal and4_i_read_reg_847 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_val_V_7_read_reg_852 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_read_reg_857 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_9_read_reg_863 : STD_LOGIC_VECTOR (7 downto 0);
    signal loopWidth_read_reg_869 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1869_1_cast_fu_396_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1869_1_cast_reg_874 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1869_cast_fu_400_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1869_cast_reg_880 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_1_reg_888 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxTop_load_reg_894 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxLeft_load_reg_899 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln729_fu_428_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln729_reg_904 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1839_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hDir_load_load_fu_454_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1844_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1849_fu_469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal vDir_load_load_fu_480_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1856_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1861_fu_495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1918_fu_569_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1918_reg_941 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixIn_val_V_fu_593_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln1897_fu_677_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_val_V_8_fu_687_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_65_phi_fu_299_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_65_reg_296 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_64_phi_fu_316_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_64_reg_313 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_phi_ln1930_phi_fu_333_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln1930_fu_574_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter1_phi_ln1930_reg_330 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_val_V_4_reg_340 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_val_V_4_reg_340 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_val_V_4_reg_340 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_val_V_4_reg_340 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_val_V_3_reg_357 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_val_V_3_reg_357 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_val_V_3_reg_357 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_val_V_3_reg_357 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_val_V_reg_376 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_val_V_reg_376 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_val_V_reg_376 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_val_V_reg_376 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1930_fu_583_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln1866_fu_516_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1870_fu_540_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_fu_126 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_2_fu_437_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal boxTop_fu_130 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxLeft_fu_134 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal or_ln1839_fu_443_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln1869_fu_506_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1867_fu_511_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln1873_fu_530_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1871_fu_535_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1918_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1887_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxBottom_fu_628_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1892_fu_649_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxRight_fu_623_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1887_1_fu_644_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1887_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1892_1_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1892_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1897_2_fu_671_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1897_1_fu_665_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1902_fu_683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_val_V_14_fu_700_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_13_fu_693_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1946_fu_721_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_15_fu_707_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_728_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_val_V_16_fu_714_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_290 : BOOLEAN;
    signal ap_condition_385 : BOOLEAN;
    signal ap_condition_224 : BOOLEAN;
    signal ap_condition_669 : BOOLEAN;
    signal ap_condition_412 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component vid_oe1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2_whiYuv_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component vid_oe1_v_tpg_0_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    whiYuv_2_U : component vid_oe1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2_whiYuv_2_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => whiYuv_2_address0,
        ce0 => whiYuv_2_ce0,
        q0 => whiYuv_2_q0);

    flow_control_loop_pipe_sequential_init_U : component vid_oe1_v_tpg_0_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_pix_val_V_3_reg_357_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_224)) then
                if ((ap_const_boolean_1 = ap_condition_385)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_3_reg_357 <= ap_const_lv8_F0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_3_reg_357 <= ap_phi_reg_pp0_iter1_pix_val_V_3_reg_357;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_val_V_4_reg_340_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_224)) then
                if ((ap_const_boolean_1 = ap_condition_385)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_4_reg_340 <= pixOut_val_V_read_reg_857;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_4_reg_340 <= ap_phi_reg_pp0_iter1_pix_val_V_4_reg_340;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_val_V_reg_376_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_224)) then
                if ((ap_const_boolean_1 = ap_condition_385)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_reg_376 <= ap_const_lv8_F0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_val_V_reg_376 <= ap_phi_reg_pp0_iter1_pix_val_V_reg_376;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_val_V_3_reg_357_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((color_read_reg_779 = ap_const_lv8_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (or_ln1918_reg_941 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_2))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_3_reg_357 <= whiYuv_2_q0;
            elsif (((ap_const_lv1_1 = and_ln1897_fu_677_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_3_reg_357 <= pixOut_val_V_8_fu_687_p3;
            elsif (((not((ovrlayId_load_read_reg_826 = ap_const_lv8_2)) and not((ovrlayId_load_read_reg_826 = ap_const_lv8_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (or_ln1918_reg_941 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln1897_fu_677_p2) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1)))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_3_reg_357 <= bckgndYUV_dout(15 downto 8);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_3_reg_357 <= ap_phi_reg_pp0_iter2_pix_val_V_3_reg_357;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_val_V_4_reg_340_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((color_read_reg_779 = ap_const_lv8_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (or_ln1918_reg_941 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_2))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_4_reg_340 <= pixOut_val_V_read_reg_857;
            elsif (((ap_const_lv1_1 = and_ln1897_fu_677_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_4_reg_340 <= pixOut_val_V_9_read_reg_863;
            elsif (((not((ovrlayId_load_read_reg_826 = ap_const_lv8_2)) and not((ovrlayId_load_read_reg_826 = ap_const_lv8_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (or_ln1918_reg_941 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln1897_fu_677_p2) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1)))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_4_reg_340 <= bckgndYUV_dout(23 downto 16);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_4_reg_340 <= ap_phi_reg_pp0_iter2_pix_val_V_4_reg_340;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_val_V_reg_376_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((color_read_reg_779 = ap_const_lv8_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (or_ln1918_reg_941 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_2))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_reg_376 <= ap_const_lv8_F0;
            elsif (((ap_const_lv1_1 = and_ln1897_fu_677_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_reg_376 <= pixOut_val_V_7_read_reg_852;
            elsif (((not((ovrlayId_load_read_reg_826 = ap_const_lv8_2)) and not((ovrlayId_load_read_reg_826 = ap_const_lv8_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (or_ln1918_reg_941 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln1897_fu_677_p2) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1)))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_reg_376 <= pixIn_val_V_fu_593_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_val_V_reg_376 <= ap_phi_reg_pp0_iter2_pix_val_V_reg_376;
            end if; 
        end if;
    end process;

    boxLeft_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    boxLeft_fu_134 <= boxHCoord_loc_0;
                elsif ((ap_const_boolean_1 = ap_condition_669)) then 
                    boxLeft_fu_134 <= select_ln1866_fu_516_p3;
                end if;
            end if; 
        end if;
    end process;

    boxTop_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    boxTop_fu_130 <= boxVCoord_loc_0;
                elsif ((ap_const_boolean_1 = ap_condition_669)) then 
                    boxTop_fu_130 <= select_ln1870_fu_540_p3;
                end if;
            end if; 
        end if;
    end process;

    hDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_412)) then
                if (((icmp_ln1849_fu_469_p2 = ap_const_lv1_1) and (hDir_load_load_fu_454_p1 = ap_const_lv1_1))) then 
                    hDir <= ap_const_lv1_0;
                elsif (((icmp_ln1844_fu_458_p2 = ap_const_lv1_1) and (hDir_load_load_fu_454_p1 = ap_const_lv1_0))) then 
                    hDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    vDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_412)) then
                if (((icmp_ln1861_fu_495_p2 = ap_const_lv1_1) and (vDir_load_load_fu_480_p1 = ap_const_lv1_1))) then 
                    vDir <= ap_const_lv1_0;
                elsif (((icmp_ln1856_fu_484_p2 = ap_const_lv1_1) and (vDir_load_load_fu_480_p1 = ap_const_lv1_0))) then 
                    vDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    x_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_126 <= ap_const_lv16_0;
                elsif (((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    x_fu_126 <= x_2_fu_437_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and10_i_read_reg_830 <= and10_i;
                and26_i_read_reg_842 <= and26_i;
                and4_i_read_reg_847 <= and4_i;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                boxColorG_1_read_reg_793 <= boxColorG_1;
                boxSize_1_read_reg_820 <= boxSize_1;
                cmp101_i_read_reg_798 <= cmp101_i;
                color_read_reg_779 <= color;
                crossHairX_1_read_reg_788 <= crossHairX_1;
                hMax_read_reg_803 <= hMax;
                icmp_ln729_reg_909 <= icmp_ln729_fu_432_p2;
                loopWidth_read_reg_869 <= loopWidth;
                ovrlayId_load_read_reg_826 <= ovrlayId_load;
                pixOut_val_V_7_read_reg_852 <= pixOut_val_V_7;
                pixOut_val_V_9_read_reg_863 <= pixOut_val_V_9;
                pixOut_val_V_read_reg_857 <= pixOut_val_V;
                tobool_read_reg_835 <= tobool;
                trunc_ln729_reg_904 <= trunc_ln729_fu_428_p1;
                vMax_read_reg_808 <= vMax;
                x_1_reg_888 <= x_fu_126;
                    zext_ln1869_1_cast_reg_874(8 downto 0) <= zext_ln1869_1_cast_fu_396_p1(8 downto 0);
                    zext_ln1869_cast_reg_880(7 downto 0) <= zext_ln1869_cast_fu_400_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_pix_val_V_3_reg_357 <= ap_phi_reg_pp0_iter0_pix_val_V_3_reg_357;
                ap_phi_reg_pp0_iter1_pix_val_V_4_reg_340 <= ap_phi_reg_pp0_iter0_pix_val_V_4_reg_340;
                ap_phi_reg_pp0_iter1_pix_val_V_reg_376 <= ap_phi_reg_pp0_iter0_pix_val_V_reg_376;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                boxLeft_load_reg_899 <= boxLeft_fu_134;
                boxTop_load_reg_894 <= boxTop_fu_130;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ovrlayId_load_read_reg_826 = ap_const_lv8_2))) then
                or_ln1918_reg_941 <= or_ln1918_fu_569_p2;
            end if;
        end if;
    end process;
    zext_ln1869_1_cast_reg_874(15 downto 9) <= "0000000";
    zext_ln1869_cast_reg_880(15 downto 8) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1867_fu_511_p2 <= std_logic_vector(unsigned(boxLeft_fu_134) + unsigned(zext_ln1869_cast_reg_880));
    add_ln1871_fu_535_p2 <= std_logic_vector(unsigned(boxTop_fu_130) + unsigned(zext_ln1869_cast_reg_880));
    and_ln1897_1_fu_665_p2 <= (xor_ln1887_fu_638_p2 and icmp_ln1887_1_fu_644_p2);
    and_ln1897_2_fu_671_p2 <= (xor_ln1892_fu_654_p2 and icmp_ln1892_1_fu_660_p2);
    and_ln1897_fu_677_p2 <= (and_ln1897_2_fu_671_p2 and and_ln1897_1_fu_665_p2);
    and_ln1902_fu_683_p2 <= (trunc_ln729_reg_904 and cmp101_i_read_reg_798);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, bckgndYUV_empty_n, icmp_ln729_reg_909, ovrlayYUV_full_n)
    begin
                ap_block_pp0_stage0_01001 <= (((ovrlayYUV_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((icmp_ln729_reg_909 = ap_const_lv1_0) and (bckgndYUV_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, bckgndYUV_empty_n, icmp_ln729_reg_909, ovrlayYUV_full_n)
    begin
                ap_block_pp0_stage0_11001 <= (((ovrlayYUV_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((icmp_ln729_reg_909 = ap_const_lv1_0) and (bckgndYUV_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, bckgndYUV_empty_n, icmp_ln729_reg_909, ovrlayYUV_full_n)
    begin
                ap_block_pp0_stage0_subdone <= (((ovrlayYUV_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((icmp_ln729_reg_909 = ap_const_lv1_0) and (bckgndYUV_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(bckgndYUV_empty_n, icmp_ln729_reg_909)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((icmp_ln729_reg_909 = ap_const_lv1_0) and (bckgndYUV_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(ovrlayYUV_full_n)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (ovrlayYUV_full_n = ap_const_logic_0);
    end process;


    ap_condition_224_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_224 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_290_assign_proc : process(icmp_ln729_fu_432_p2, ovrlayId_load_read_reg_826, or_ln1918_fu_569_p2)
    begin
                ap_condition_290 <= ((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (or_ln1918_fu_569_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_2));
    end process;


    ap_condition_385_assign_proc : process(icmp_ln729_fu_432_p2, color_read_reg_779, ovrlayId_load_read_reg_826, or_ln1918_fu_569_p2)
    begin
                ap_condition_385 <= ((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (or_ln1918_fu_569_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_2) and (color_read_reg_779 = ap_const_lv8_0));
    end process;


    ap_condition_412_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln729_fu_432_p2, ap_block_pp0_stage0_11001, ovrlayId_load_read_reg_826, icmp_ln1839_fu_448_p2)
    begin
                ap_condition_412 <= ((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1));
    end process;


    ap_condition_669_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln729_fu_432_p2, ovrlayId_load_read_reg_826, icmp_ln1839_fu_448_p2)
    begin
                ap_condition_669 <= ((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln729_fu_432_p2)
    begin
        if (((icmp_ln729_fu_432_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_empty_64_phi_fu_316_p8_assign_proc : process(icmp_ln729_fu_432_p2, ovrlayId_load_read_reg_826, icmp_ln1839_fu_448_p2, vDir_load_load_fu_480_p1, icmp_ln1856_fu_484_p2, icmp_ln1861_fu_495_p2, ap_phi_reg_pp0_iter1_empty_64_reg_313)
    begin
        if ((((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (icmp_ln1861_fu_495_p2 = ap_const_lv1_0) and (vDir_load_load_fu_480_p1 = ap_const_lv1_1) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1)) or ((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (icmp_ln1856_fu_484_p2 = ap_const_lv1_1) and (vDir_load_load_fu_480_p1 = ap_const_lv1_0) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_64_phi_fu_316_p8 <= ap_const_lv1_1;
        elsif ((((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (icmp_ln1856_fu_484_p2 = ap_const_lv1_0) and (vDir_load_load_fu_480_p1 = ap_const_lv1_0) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1)) or ((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (icmp_ln1861_fu_495_p2 = ap_const_lv1_1) and (vDir_load_load_fu_480_p1 = ap_const_lv1_1) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_64_phi_fu_316_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_empty_64_phi_fu_316_p8 <= ap_phi_reg_pp0_iter1_empty_64_reg_313;
        end if; 
    end process;


    ap_phi_mux_empty_65_phi_fu_299_p8_assign_proc : process(icmp_ln729_fu_432_p2, ovrlayId_load_read_reg_826, icmp_ln1839_fu_448_p2, hDir_load_load_fu_454_p1, icmp_ln1844_fu_458_p2, icmp_ln1849_fu_469_p2, ap_phi_reg_pp0_iter1_empty_65_reg_296)
    begin
        if ((((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (icmp_ln1849_fu_469_p2 = ap_const_lv1_0) and (hDir_load_load_fu_454_p1 = ap_const_lv1_1) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1)) or ((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (icmp_ln1844_fu_458_p2 = ap_const_lv1_1) and (hDir_load_load_fu_454_p1 = ap_const_lv1_0) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_65_phi_fu_299_p8 <= ap_const_lv1_1;
        elsif ((((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (icmp_ln1844_fu_458_p2 = ap_const_lv1_0) and (hDir_load_load_fu_454_p1 = ap_const_lv1_0) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1)) or ((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (icmp_ln1849_fu_469_p2 = ap_const_lv1_1) and (hDir_load_load_fu_454_p1 = ap_const_lv1_1) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_65_phi_fu_299_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_empty_65_phi_fu_299_p8 <= ap_phi_reg_pp0_iter1_empty_65_reg_296;
        end if; 
    end process;


    ap_phi_mux_phi_ln1930_phi_fu_333_p4_assign_proc : process(color_read_reg_779, select_ln1930_fu_574_p3, ap_phi_reg_pp0_iter1_phi_ln1930_reg_330, ap_condition_290)
    begin
        if ((ap_const_boolean_1 = ap_condition_290)) then
            if ((color_read_reg_779 = ap_const_lv8_1)) then 
                ap_phi_mux_phi_ln1930_phi_fu_333_p4 <= ap_const_lv2_1;
            elsif ((not((color_read_reg_779 = ap_const_lv8_1)) and not((color_read_reg_779 = ap_const_lv8_0)))) then 
                ap_phi_mux_phi_ln1930_phi_fu_333_p4 <= select_ln1930_fu_574_p3;
            else 
                ap_phi_mux_phi_ln1930_phi_fu_333_p4 <= ap_phi_reg_pp0_iter1_phi_ln1930_reg_330;
            end if;
        else 
            ap_phi_mux_phi_ln1930_phi_fu_333_p4 <= ap_phi_reg_pp0_iter1_phi_ln1930_reg_330;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_pix_val_V_3_reg_357 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_val_V_4_reg_340 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_val_V_reg_376 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter1_empty_64_reg_313 <= "X";
    ap_phi_reg_pp0_iter1_empty_65_reg_296 <= "X";
    ap_phi_reg_pp0_iter1_phi_ln1930_reg_330 <= "XX";

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    bckgndYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, bckgndYUV_empty_n, icmp_ln729_reg_909, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            bckgndYUV_blk_n <= bckgndYUV_empty_n;
        else 
            bckgndYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bckgndYUV_read_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln729_reg_909, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            bckgndYUV_read <= ap_const_logic_1;
        else 
            bckgndYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    boxBottom_fu_628_p2 <= std_logic_vector(unsigned(boxSize_1_read_reg_820) + unsigned(boxTop_fu_130));
    boxHCoord <= 
        sub_ln1869_fu_506_p2 when (ap_phi_mux_empty_65_phi_fu_299_p8(0) = '1') else 
        add_ln1867_fu_511_p2;

    boxHCoord_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln729_fu_432_p2, ap_block_pp0_stage0_11001, ovrlayId_load_read_reg_826, icmp_ln1839_fu_448_p2)
    begin
        if (((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1))) then 
            boxHCoord_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxHCoord_loc_1_out <= boxLeft_load_reg_899;

    boxHCoord_loc_1_out_ap_vld_assign_proc : process(icmp_ln729_reg_909, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_1))) then 
            boxHCoord_loc_1_out_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_loc_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxRight_fu_623_p2 <= std_logic_vector(unsigned(boxSize_1_read_reg_820) + unsigned(boxLeft_fu_134));
    boxVCoord <= 
        sub_ln1873_fu_530_p2 when (ap_phi_mux_empty_64_phi_fu_316_p8(0) = '1') else 
        add_ln1871_fu_535_p2;

    boxVCoord_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln729_fu_432_p2, ap_block_pp0_stage0_11001, ovrlayId_load_read_reg_826, icmp_ln1839_fu_448_p2)
    begin
        if (((icmp_ln729_fu_432_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1839_fu_448_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ovrlayId_load_read_reg_826 = ap_const_lv8_1))) then 
            boxVCoord_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxVCoord_loc_1_out <= boxTop_load_reg_894;

    boxVCoord_loc_1_out_ap_vld_assign_proc : process(icmp_ln729_reg_909, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln729_reg_909 = ap_const_lv1_1))) then 
            boxVCoord_loc_1_out_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_loc_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_728_p3 <= 
        ap_phi_reg_pp0_iter3_pix_val_V_3_reg_357 when (tobool_read_reg_835(0) = '1') else 
        select_ln1946_fu_721_p3;
    hDir_load_load_fu_454_p1 <= hDir;
    icmp_ln1839_fu_448_p2 <= "1" when (or_ln1839_fu_443_p2 = ap_const_lv16_0) else "0";
    icmp_ln1844_fu_458_p2 <= "1" when (unsigned(boxLeft_fu_134) > unsigned(hMax_read_reg_803)) else "0";
    icmp_ln1849_fu_469_p2 <= "1" when (unsigned(zext_ln1869_1_cast_reg_874) > unsigned(boxLeft_fu_134)) else "0";
    icmp_ln1856_fu_484_p2 <= "1" when (unsigned(boxTop_fu_130) > unsigned(vMax_read_reg_808)) else "0";
    icmp_ln1861_fu_495_p2 <= "1" when (unsigned(zext_ln1869_1_cast_reg_874) > unsigned(boxTop_fu_130)) else "0";
    icmp_ln1887_1_fu_644_p2 <= "1" when (unsigned(y) < unsigned(boxBottom_fu_628_p2)) else "0";
    icmp_ln1887_fu_633_p2 <= "1" when (unsigned(y) < unsigned(boxTop_fu_130)) else "0";
    icmp_ln1892_1_fu_660_p2 <= "1" when (unsigned(x_1_reg_888) < unsigned(boxRight_fu_623_p2)) else "0";
    icmp_ln1892_fu_649_p2 <= "1" when (unsigned(x_1_reg_888) < unsigned(boxLeft_fu_134)) else "0";
    icmp_ln1918_fu_564_p2 <= "1" when (x_fu_126 = crossHairX_1_read_reg_788) else "0";
    icmp_ln729_fu_432_p2 <= "1" when (x_fu_126 = loopWidth_read_reg_869) else "0";
    or_ln1839_fu_443_p2 <= (y or x_fu_126);
    or_ln1918_fu_569_p2 <= (icmp_ln1918_fu_564_p2 or cmp2_i);

    ovrlayYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, ovrlayYUV_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ovrlayYUV_blk_n <= ovrlayYUV_full_n;
        else 
            ovrlayYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ovrlayYUV_din <= ((pixOut_val_V_15_fu_707_p3 & empty_fu_728_p3) & pixOut_val_V_16_fu_714_p3);

    ovrlayYUV_write_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ovrlayYUV_write <= ap_const_logic_1;
        else 
            ovrlayYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    pixIn_val_V_fu_593_p1 <= bckgndYUV_dout(8 - 1 downto 0);
    pixOut_val_V_13_fu_693_p3 <= 
        ap_const_lv8_0 when (and4_i_read_reg_847(0) = '1') else 
        ap_phi_reg_pp0_iter3_pix_val_V_reg_376;
    pixOut_val_V_14_fu_700_p3 <= 
        ap_const_lv8_0 when (and26_i_read_reg_842(0) = '1') else 
        ap_phi_reg_pp0_iter3_pix_val_V_4_reg_340;
    pixOut_val_V_15_fu_707_p3 <= 
        ap_phi_reg_pp0_iter3_pix_val_V_4_reg_340 when (tobool_read_reg_835(0) = '1') else 
        pixOut_val_V_14_fu_700_p3;
    pixOut_val_V_16_fu_714_p3 <= 
        ap_phi_reg_pp0_iter3_pix_val_V_reg_376 when (tobool_read_reg_835(0) = '1') else 
        pixOut_val_V_13_fu_693_p3;
    pixOut_val_V_8_fu_687_p3 <= 
        pixOut_val_V_9_read_reg_863 when (and_ln1902_fu_683_p2(0) = '1') else 
        boxColorG_1_read_reg_793;
    select_ln1866_fu_516_p3 <= 
        sub_ln1869_fu_506_p2 when (ap_phi_mux_empty_65_phi_fu_299_p8(0) = '1') else 
        add_ln1867_fu_511_p2;
    select_ln1870_fu_540_p3 <= 
        sub_ln1873_fu_530_p2 when (ap_phi_mux_empty_64_phi_fu_316_p8(0) = '1') else 
        add_ln1871_fu_535_p2;
    select_ln1930_fu_574_p3 <= 
        ap_const_lv2_2 when (trunc_ln729_fu_428_p1(0) = '1') else 
        ap_const_lv2_1;
    select_ln1946_fu_721_p3 <= 
        ap_const_lv8_0 when (and10_i_read_reg_830(0) = '1') else 
        ap_phi_reg_pp0_iter3_pix_val_V_3_reg_357;
    sub_ln1869_fu_506_p2 <= std_logic_vector(unsigned(boxLeft_fu_134) - unsigned(zext_ln1869_cast_reg_880));
    sub_ln1873_fu_530_p2 <= std_logic_vector(unsigned(boxTop_fu_130) - unsigned(zext_ln1869_cast_reg_880));
    trunc_ln729_fu_428_p1 <= x_fu_126(1 - 1 downto 0);
    vDir_load_load_fu_480_p1 <= vDir;
    whiYuv_2_address0 <= zext_ln1930_fu_583_p1(2 - 1 downto 0);

    whiYuv_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            whiYuv_2_ce0 <= ap_const_logic_1;
        else 
            whiYuv_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_2_fu_437_p2 <= std_logic_vector(unsigned(x_fu_126) + unsigned(ap_const_lv16_1));
    xor_ln1887_fu_638_p2 <= (icmp_ln1887_fu_633_p2 xor ap_const_lv1_1);
    xor_ln1892_fu_654_p2 <= (icmp_ln1892_fu_649_p2 xor ap_const_lv1_1);
    zext_ln1869_1_cast_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln1869_1),16));
    zext_ln1869_cast_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln1869),16));
    zext_ln1930_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_phi_ln1930_phi_fu_333_p4),64));
end behav;
