# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sean/Downloads/git/ECE385_FP/VID_OE3/VID_OE3.srcs/sources_1/bd/vid_oe3/ip/vid_oe3_microblaze_0_axi_intc_1/vid_oe3_microblaze_0_axi_intc_1.xci
# IP: The module: 'vid_oe3_microblaze_0_axi_intc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE3/VID_OE3.gen/sources_1/bd/vid_oe3/ip/vid_oe3_microblaze_0_axi_intc_1/vid_oe3_microblaze_0_axi_intc_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe3_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE3/VID_OE3.gen/sources_1/bd/vid_oe3/ip/vid_oe3_microblaze_0_axi_intc_1/vid_oe3_microblaze_0_axi_intc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe3_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE3/VID_OE3.gen/sources_1/bd/vid_oe3/ip/vid_oe3_microblaze_0_axi_intc_1/vid_oe3_microblaze_0_axi_intc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe3_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/sean/Downloads/git/ECE385_FP/VID_OE3/VID_OE3.srcs/sources_1/bd/vid_oe3/ip/vid_oe3_microblaze_0_axi_intc_1/vid_oe3_microblaze_0_axi_intc_1.xci
# IP: The module: 'vid_oe3_microblaze_0_axi_intc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE3/VID_OE3.gen/sources_1/bd/vid_oe3/ip/vid_oe3_microblaze_0_axi_intc_1/vid_oe3_microblaze_0_axi_intc_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe3_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE3/VID_OE3.gen/sources_1/bd/vid_oe3/ip/vid_oe3_microblaze_0_axi_intc_1/vid_oe3_microblaze_0_axi_intc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe3_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/VID_OE3/VID_OE3.gen/sources_1/bd/vid_oe3/ip/vid_oe3_microblaze_0_axi_intc_1/vid_oe3_microblaze_0_axi_intc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vid_oe3_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
