# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.runs/synth_1/bd_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param gui.addressMap 0
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.cache/wt [current_project]
set_property parent.project_path /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/hdl/bd_wrapper.v
add_files /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.srcs/sources_1/bd/bd/bd.bd
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_1/bd_2327_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_1/bd_2327_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_2/bd_2327_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_2/bd_2327_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_3/bd_2327_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_3/bd_2327_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_4/bd_2327_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_5/bd_2327_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_6/bd_2327_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_7/bd_2327_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_8/bd_2327_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_12/bd_2327_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_13/bd_2327_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_14/bd_2327_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_15/bd_2327_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_16/bd_2327_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_17/bd_2327_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_21/bd_2327_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_22/bd_2327_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_23/bd_2327_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_27/bd_2327_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_28/bd_2327_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_29/bd_2327_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_30/bd_2327_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_31/bd_2327_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_32/bd_2327_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_33/bd_2327_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_34/bd_2327_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_35/bd_2327_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_36/bd_2327_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_37/bd_2327_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_38/bd_2327_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_40/bd_2327_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_41/bd_2327_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_42/bd_2327_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_43/bd_2327_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_44/bd_2327_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/bd_0/ip/ip_45/bd_2327_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_uartlite_0_0/bd_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_uartlite_0_0/bd_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_axi_uartlite_0_0/bd_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_clk_wiz_1_0/bd_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_clk_wiz_1_0/bd_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_clk_wiz_1_0/bd_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_mdm_1_0/bd_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_mdm_1_0/bd_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_microblaze_0_0/bd_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_microblaze_0_0/bd_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_microblaze_0_0/bd_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_dlmb_bram_if_cntlr_0/bd_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_dlmb_v10_0/bd_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_ilmb_bram_if_cntlr_0/bd_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_ilmb_v10_0/bd_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_lmb_bram_0/bd_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_mig_7series_0_0/bd_mig_7series_0_0/user_design/constraints/bd_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_mig_7series_0_0/bd_mig_7series_0_0/user_design/constraints/bd_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_rst_clk_wiz_1_100M_0/bd_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_rst_clk_wiz_1_100M_0/bd_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_rst_clk_wiz_1_100M_0/bd_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_rst_mig_7series_0_166M_0/bd_rst_mig_7series_0_166M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_rst_mig_7series_0_166M_0/bd_rst_mig_7series_0_166M_0.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_rst_mig_7series_0_166M_0/bd_rst_mig_7series_0_166M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/bd_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/ip/bd_microblaze_0_0/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.srcs/constrs_1/imports/constraints/bd-mem.xdc
set_property used_in_implementation false [get_files /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.srcs/constrs_1/imports/constraints/bd-mem.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top bd_wrapper -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bd_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bd_wrapper_utilization_synth.rpt -pb bd_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
