# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/bd-mem.xdc

# Block Designs: bd/bd/bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd || ORIG_REF_NAME==bd} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_smc_0/bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_smc_0 || ORIG_REF_NAME==bd_axi_smc_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_uartlite_0_0/bd_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_uartlite_0_0 || ORIG_REF_NAME==bd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_clk_wiz_1_0/bd_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_clk_wiz_1_0 || ORIG_REF_NAME==bd_clk_wiz_1_0} -quiet] -quiet

# IP: bd/bd/ip/bd_mdm_1_0/bd_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mdm_1_0 || ORIG_REF_NAME==bd_mdm_1_0} -quiet] -quiet

# IP: bd/bd/ip/bd_microblaze_0_0/bd_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_microblaze_0_0 || ORIG_REF_NAME==bd_microblaze_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_dlmb_bram_if_cntlr_0/bd_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd/ip/bd_dlmb_v10_0/bd_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dlmb_v10_0 || ORIG_REF_NAME==bd_dlmb_v10_0} -quiet] -quiet

# IP: bd/bd/ip/bd_ilmb_bram_if_cntlr_0/bd_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd/ip/bd_ilmb_v10_0/bd_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ilmb_v10_0 || ORIG_REF_NAME==bd_ilmb_v10_0} -quiet] -quiet

# IP: bd/bd/ip/bd_lmb_bram_0/bd_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_lmb_bram_0 || ORIG_REF_NAME==bd_lmb_bram_0} -quiet] -quiet

# IP: bd/bd/ip/bd_mig_7series_0_0/bd_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mig_7series_0_0 || ORIG_REF_NAME==bd_mig_7series_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_rst_clk_wiz_1_100M_0/bd_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==bd_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/bd/ip/bd_rst_mig_7series_0_166M_0/bd_rst_mig_7series_0_166M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_rst_mig_7series_0_166M_0 || ORIG_REF_NAME==bd_rst_mig_7series_0_166M_0} -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/DDR3_RE1/DDR3_RE1.gen/sources_1/bd/bd/bd_ooc.xdc
