# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/DDR3_provided_files/urbana_ddr3.xdc

# Block Designs: bd/mb_bram_ddr3/mb_bram_ddr3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3 || ORIG_REF_NAME==mb_bram_ddr3} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_mig_7series_0_0/mb_bram_ddr3_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_mig_7series_0_0 || ORIG_REF_NAME==mb_bram_ddr3_mig_7series_0_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_microblaze_0_0/mb_bram_ddr3_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_microblaze_0_0 || ORIG_REF_NAME==mb_bram_ddr3_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_xbar_0/mb_bram_ddr3_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_xbar_0 || ORIG_REF_NAME==mb_bram_ddr3_xbar_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_microblaze_0_axi_periph_0/mb_bram_ddr3_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_bram_ddr3_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_microblaze_0_axi_intc_0/mb_bram_ddr3_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_bram_ddr3_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_microblaze_0_xlconcat_0/mb_bram_ddr3_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_bram_ddr3_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_mdm_1_0/mb_bram_ddr3_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_mdm_1_0 || ORIG_REF_NAME==mb_bram_ddr3_mdm_1_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_rst_mig_7series_0_83M_0/mb_bram_ddr3_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==mb_bram_ddr3_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_axi_uartlite_0_0/mb_bram_ddr3_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_axi_uartlite_0_0 || ORIG_REF_NAME==mb_bram_ddr3_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_axi_timer_0_0/mb_bram_ddr3_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_axi_timer_0_0 || ORIG_REF_NAME==mb_bram_ddr3_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_pc_3/mb_bram_ddr3_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_auto_pc_3 || ORIG_REF_NAME==mb_bram_ddr3_auto_pc_3} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_us_0/mb_bram_ddr3_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_auto_us_0 || ORIG_REF_NAME==mb_bram_ddr3_auto_us_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_us_1/mb_bram_ddr3_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_auto_us_1 || ORIG_REF_NAME==mb_bram_ddr3_auto_us_1} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_us_2/mb_bram_ddr3_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_auto_us_2 || ORIG_REF_NAME==mb_bram_ddr3_auto_us_2} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_ds_0/mb_bram_ddr3_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_auto_ds_0 || ORIG_REF_NAME==mb_bram_ddr3_auto_ds_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_pc_0/mb_bram_ddr3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_auto_pc_0 || ORIG_REF_NAME==mb_bram_ddr3_auto_pc_0} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_ds_1/mb_bram_ddr3_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_auto_ds_1 || ORIG_REF_NAME==mb_bram_ddr3_auto_ds_1} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_pc_1/mb_bram_ddr3_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_auto_pc_1 || ORIG_REF_NAME==mb_bram_ddr3_auto_pc_1} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_ds_2/mb_bram_ddr3_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_auto_ds_2 || ORIG_REF_NAME==mb_bram_ddr3_auto_ds_2} -quiet] -quiet

# IP: bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_pc_2/mb_bram_ddr3_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_bram_ddr3_auto_pc_2 || ORIG_REF_NAME==mb_bram_ddr3_auto_pc_2} -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/MB_BRAM_IMPL/MB_BRAM_IMPL.gen/sources_1/bd/mb_bram_ddr3/mb_bram_ddr3_ooc.xdc
