# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sean/Downloads/git/ECE385_FP/MB_BRAM_IMPL/MB_BRAM_IMPL.srcs/sources_1/bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_us_2/mb_bram_ddr3_auto_us_2.xci
# IP: The module: 'mb_bram_ddr3_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sean/Downloads/git/ECE385_FP/MB_BRAM_IMPL/MB_BRAM_IMPL.gen/sources_1/bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_us_2/mb_bram_ddr3_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_bram_ddr3_auto_us_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/MB_BRAM_IMPL/MB_BRAM_IMPL.gen/sources_1/bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_us_2/mb_bram_ddr3_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_bram_ddr3_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/sean/Downloads/git/ECE385_FP/MB_BRAM_IMPL/MB_BRAM_IMPL.srcs/sources_1/bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_us_2/mb_bram_ddr3_auto_us_2.xci
# IP: The module: 'mb_bram_ddr3_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sean/Downloads/git/ECE385_FP/MB_BRAM_IMPL/MB_BRAM_IMPL.gen/sources_1/bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_us_2/mb_bram_ddr3_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_bram_ddr3_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/sean/Downloads/git/ECE385_FP/MB_BRAM_IMPL/MB_BRAM_IMPL.gen/sources_1/bd/mb_bram_ddr3/ip/mb_bram_ddr3_auto_us_2/mb_bram_ddr3_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_bram_ddr3_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
