# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sean/Downloads/git/ECE385_FP/ip_repo/frame_buffer_1_0/src/axi_bram_ctl/axi_bram_ctl.xci
# IP: The module: 'axi_bram_ctl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sean/Downloads/git/ECE385_FP/ip_repo/frame_buffer_1_0/src/axi_bram_ctl/axi_bram_ctl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram_ctl'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/sean/Downloads/git/ECE385_FP/ip_repo/frame_buffer_1_0/src/axi_bram_ctl/axi_bram_ctl.xci
# IP: The module: 'axi_bram_ctl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sean/Downloads/git/ECE385_FP/ip_repo/frame_buffer_1_0/src/axi_bram_ctl/axi_bram_ctl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram_ctl'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
